language: node_js
node_js: stable
notifications:
  email:
    on_success: never
    on_failure: never
# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - hexo generate

after_script:
  - cd public
  - ls

branches:
  only:
    - master
