version: 2
jobs:
  generate-page:
    docker:
      - image: node:8.11.1
    steps:
      - checkout
      - run:
          name: 安装hexo
          command: npm install -g hexo-cli
      - run:
          name: 安装依赖
          command: npm install
      - run:
          name:  查看内容
          command: |
            ls
            ls themes
            cd themes
            ls 3-hexo
            cd ..
            echo "submodule init."
            git submodule init 
            echo "submodule update."
            git submodule update
            cd themes
            ls 3-hexo
      - run:
          name:  生成页面
          command: hexo generate
      - run:
          name: 部署Github Pages
          command: |
            cd public
            ls
            git init
            git config user.name "$GH_USER"
            git config user.email "$GH_EMAIL"
            git add .
            git commit -m "update"
            git push --force --quiet "https://$GH_TOKEN@$GH_REF" master
            echo 'deploy success'
workflows:
  version: 2
  build-deploy:
    jobs:
      - generate-page:
          filters:
            branches:
              only: master